### ISSUE TITLE
以 timeline 的形式显示旺旺信息

### ISSUE THREAD

**Issue by fengmk2** [fengmk2/wangwang#1]
不喜欢一大堆窗口, 不喜欢信息消息都在最下面...
- 以 timeline 形式显示所有旺旺信息, 能区分私聊还是群聊
- 可以直接回复私聊和群聊
- 能方便地取回群聊上下文
- 点击头像能打开单独的聊天窗口

**Comment by dead-horse** [comment]
用 atom-shell 写一个旺旺？

**Comment by fengmk2** [comment]
是的
2014-8-14 上午10:30于 "dead_horse" notifications@github.com写道：

**Comment by dead-horse** [comment]
++

有接口么？受不了 mac 旺旺了..
